package com.mycompany.models;


// Generated 12/09/2015 04:52:35 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DetalleFacturaId generated by hbm2java
 */
@Embeddable
public class DetalleFacturaId  implements java.io.Serializable {

    private static final long serialVersionUID = 3237914100408508473L;
     private int productosEnVentaIdProductosEnVenta;
     private int facturasIdFacturas;

    public DetalleFacturaId() {
    }

    public DetalleFacturaId(int productosEnVentaIdProductosEnVenta, int facturasIdFacturas) {
       this.productosEnVentaIdProductosEnVenta = productosEnVentaIdProductosEnVenta;
       this.facturasIdFacturas = facturasIdFacturas;
    }
   


    @Column(name="ProductosEnVenta_idProductosEnVenta", nullable=false)
    public int getProductosEnVentaIdProductosEnVenta() {
        return this.productosEnVentaIdProductosEnVenta;
    }
    
    public void setProductosEnVentaIdProductosEnVenta(int productosEnVentaIdProductosEnVenta) {
        this.productosEnVentaIdProductosEnVenta = productosEnVentaIdProductosEnVenta;
    }


    @Column(name="Facturas_idFacturas", nullable=false)
    public int getFacturasIdFacturas() {
        return this.facturasIdFacturas;
    }
    
    public void setFacturasIdFacturas(int facturasIdFacturas) {
        this.facturasIdFacturas = facturasIdFacturas;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetalleFacturaId) ) return false;
		 DetalleFacturaId castOther = ( DetalleFacturaId ) other; 
         
		 return (this.getProductosEnVentaIdProductosEnVenta()==castOther.getProductosEnVentaIdProductosEnVenta())
 && (this.getFacturasIdFacturas()==castOther.getFacturasIdFacturas());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getProductosEnVentaIdProductosEnVenta();
         result = 37 * result + this.getFacturasIdFacturas();
         return result;
   }   


}


