package com.mycompany.models;


// Generated 12/09/2015 04:52:35 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DetalleFactura generated by hbm2java
 */
@Entity
@Table(name="DetalleFactura")
public class DetalleFactura  implements java.io.Serializable {


     private DetalleFacturaId id;
     private Factura facturas;
     private ProductoEnVenta productosEnVenta;
     private float cantidadComprada;
     private float precioVenta;
     private boolean yaSeEntrego;
     private Set<Despacho> despachoses = new HashSet<Despacho>(0);

    public DetalleFactura() {
    }

	
    public DetalleFactura(DetalleFacturaId id, Factura facturas, ProductoEnVenta productosEnVenta, float cantidadComprada, float precioVenta, boolean yaSeEntrego) {
        this.id = id;
        this.facturas = facturas;
        this.productosEnVenta = productosEnVenta;
        this.cantidadComprada = cantidadComprada;
        this.precioVenta = precioVenta;
        this.yaSeEntrego = yaSeEntrego;
    }
    public DetalleFactura(DetalleFacturaId id, Factura facturas, ProductoEnVenta productosEnVenta, float cantidadComprada, float precioVenta, boolean yaSeEntrego, Set <Despacho>despachoses) {
       this.id = id;
       this.facturas = facturas;
       this.productosEnVenta = productosEnVenta;
       this.cantidadComprada = cantidadComprada;
       this.precioVenta = precioVenta;
       this.yaSeEntrego = yaSeEntrego;
       this.despachoses = despachoses;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="productosEnVentaIdProductosEnVenta", column=@Column(name="ProductosEnVenta_idProductosEnVenta", nullable=false) ), 
        @AttributeOverride(name="facturasIdFacturas", column=@Column(name="Facturas_idFacturas", nullable=false) ) } )
    public DetalleFacturaId getId() {
        return this.id;
    }
    
    public void setId(DetalleFacturaId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Facturas_idFacturas", nullable=false, insertable=false, updatable=false)
    public Factura getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Factura facturas) {
        this.facturas = facturas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ProductosEnVenta_idProductosEnVenta", nullable=false, insertable=false, updatable=false)
    public ProductoEnVenta getProductosEnVenta() {
        return this.productosEnVenta;
    }
    
    public void setProductosEnVenta(ProductoEnVenta productosEnVenta) {
        this.productosEnVenta = productosEnVenta;
    }

    
    @Column(name="cantidadComprada", nullable=false, precision=12, scale=0)
    public float getCantidadComprada() {
        return this.cantidadComprada;
    }
    
    public void setCantidadComprada(float cantidadComprada) {
        this.cantidadComprada = cantidadComprada;
    }

    
    @Column(name="precioVenta", nullable=false, precision=12, scale=0)
    public float getPrecioVenta() {
        return this.precioVenta;
    }
    
    public void setPrecioVenta(float precioVenta) {
        this.precioVenta = precioVenta;
    }

    
    @Column(name="yaSeEntrego", nullable=false)
    public boolean isYaSeEntrego() {
        return this.yaSeEntrego;
    }
    
    public void setYaSeEntrego(boolean yaSeEntrego) {
        this.yaSeEntrego = yaSeEntrego;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="detalleFactura")
    public Set<Despacho> getDespachoses() {
        return this.despachoses;
    }
    
    public void setDespachoses(Set <Despacho>despachoses) {
        this.despachoses = despachoses;
    }




}


