package com.mycompany.models;


// Generated 12/09/2015 04:52:35 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Facturas generated by hbm2java
 */
@Entity
@Table(name="Facturas")
public class Factura  implements java.io.Serializable {


     private Integer idFacturas;
     private TransaccionBancaria transaccionesBancarias;
     private Ubicacion ubicaciones;
     private Date fecha;
     private float impuesto;
     private Set <DetalleFactura>detalleFacturas = new HashSet<DetalleFactura>(0);

    public Factura() {
    }

	
    public Factura(TransaccionBancaria transaccionesBancarias, Ubicacion ubicaciones, Date fecha, float impuesto) {
        this.transaccionesBancarias = transaccionesBancarias;
        this.ubicaciones = ubicaciones;
        this.fecha = fecha;
        this.impuesto = impuesto;
    }
    public Factura(TransaccionBancaria transaccionesBancarias, Ubicacion ubicaciones, Date fecha, float impuesto, Set<DetalleFactura> detalleFacturas) {
       this.transaccionesBancarias = transaccionesBancarias;
       this.ubicaciones = ubicaciones;
       this.fecha = fecha;
       this.impuesto = impuesto;
       this.detalleFacturas = detalleFacturas;
    }
   
     @Id @GeneratedValue

    
    @Column(name="idFacturas", unique=true, nullable=false)
    public Integer getIdFacturas() {
        return this.idFacturas;
    }
    
    public void setIdFacturas(Integer idFacturas) {
        this.idFacturas = idFacturas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TransaccionesBancarias_idTransaccionesBancarias", nullable=false)
    public TransaccionBancaria getTransaccionesBancarias() {
        return this.transaccionesBancarias;
    }
    
    public void setTransaccionesBancarias(TransaccionBancaria transaccionesBancarias) {
        this.transaccionesBancarias = transaccionesBancarias;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Ubicaciones_idUbicaciones", nullable=false)
    public Ubicacion getUbicaciones() {
        return this.ubicaciones;
    }
    
    public void setUbicaciones(Ubicacion ubicaciones) {
        this.ubicaciones = ubicaciones;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", nullable=false, length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="impuesto", nullable=false, precision=12, scale=0)
    public float getImpuesto() {
        return this.impuesto;
    }
    
    public void setImpuesto(float impuesto) {
        this.impuesto = impuesto;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="facturas")
    public Set<DetalleFactura> getDetalleFacturas() {
        return this.detalleFacturas;
    }
    
    public void setDetalleFacturas(Set <DetalleFactura>detalleFacturas) {
        this.detalleFacturas = detalleFacturas;
    }




}


