package com.mycompany.models;
// Generated Sep 8, 2015 3:54:08 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Factura generated by hbm2java
 */
@Entity
@Table(name="Facturas")
public class Factura  implements java.io.Serializable {


     private int idFacturas;
     private Minorista minoristas;
     private TransaccionBancaria transaccionesBancarias;
     private String fecha;
     private String impuesto;
     private String direccionEntrega;
     private Set<DetalleFactura> detalleFacturas = new HashSet<DetalleFactura>(0);

    public Factura() {
    }

	
    public Factura(int idFacturas, Minorista minoristas, TransaccionBancaria transaccionesBancarias, String fecha, String impuesto, String direccionEntrega) {
        this.idFacturas = idFacturas;
        this.minoristas = minoristas;
        this.transaccionesBancarias = transaccionesBancarias;
        this.fecha = fecha;
        this.impuesto = impuesto;
        this.direccionEntrega = direccionEntrega;
    }
    public Factura(int idFacturas, Minorista minoristas, TransaccionBancaria transaccionesBancarias, String fecha, String impuesto, String direccionEntrega, Set<DetalleFactura> detalleFacturas) {
       this.idFacturas = idFacturas;
       this.minoristas = minoristas;
       this.transaccionesBancarias = transaccionesBancarias;
       this.fecha = fecha;
       this.impuesto = impuesto;
       this.direccionEntrega = direccionEntrega;
       this.detalleFacturas = detalleFacturas;
    }
   
     @Id 

    
    @Column(name="idFacturas", unique=true, nullable=false)
    public int getIdFacturas() {
        return this.idFacturas;
    }
    
    public void setIdFacturas(int idFacturas) {
        this.idFacturas = idFacturas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Minoristas_idMinoristas", nullable=false)
    public Minorista getMinoristas() {
        return this.minoristas;
    }
    
    public void setMinoristas(Minorista minoristas) {
        this.minoristas = minoristas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TransaccionesBancarias_idTransaccionesBancarias", nullable=false)
    public TransaccionBancaria getTransaccionesBancarias() {
        return this.transaccionesBancarias;
    }
    
    public void setTransaccionesBancarias(TransaccionBancaria transaccionesBancarias) {
        this.transaccionesBancarias = transaccionesBancarias;
    }

    
    @Column(name="fecha", nullable=false, length=45)
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="impuesto", nullable=false, length=45)
    public String getImpuesto() {
        return this.impuesto;
    }
    
    public void setImpuesto(String impuesto) {
        this.impuesto = impuesto;
    }

    
    @Column(name="direccionEntrega", nullable=false, length=50)
    public String getDireccionEntrega() {
        return this.direccionEntrega;
    }
    
    public void setDireccionEntrega(String direccionEntrega) {
        this.direccionEntrega = direccionEntrega;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="facturas")
    public Set<DetalleFactura> getDetalleFacturas() {
        return this.detalleFacturas;
    }
    
    public void setDetalleFacturas(Set<DetalleFactura> detalleFacturas) {
        this.detalleFacturas = detalleFacturas;
    }




}


