package com.mycompany.models;
// Generated Sep 8, 2015 3:54:08 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Minorista generated by hbm2java
 */
@Entity
@Table(name="Minoristas")
public class Minorista  implements java.io.Serializable {


     private int idMinoristas;
     private String nombres;
     private String apellidos;
     private String telefono;
     private String correo;
     private Set<Factura> facturases = new HashSet<Factura>(0);
     private Set<Ubicacion> ubicacioneses = new HashSet<Ubicacion>(0);

    public Minorista() {
    }

	
    public Minorista(int idMinoristas, String nombres, String apellidos, String telefono) {
        this.idMinoristas = idMinoristas;
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.telefono = telefono;
    }
    public Minorista(int idMinoristas, String nombres, String apellidos, String telefono, String correo, Set<Factura> facturases, Set<Ubicacion> ubicacioneses) {
       this.idMinoristas = idMinoristas;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.telefono = telefono;
       this.correo = correo;
       this.facturases = facturases;
       this.ubicacioneses = ubicacioneses;
    }
   
     @Id 

    
    @Column(name="idMinoristas", unique=true, nullable=false)
    public int getIdMinoristas() {
        return this.idMinoristas;
    }
    
    public void setIdMinoristas(int idMinoristas) {
        this.idMinoristas = idMinoristas;
    }

    
    @Column(name="nombres", nullable=false, length=45)
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    
    @Column(name="apellidos", nullable=false, length=45)
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    
    @Column(name="telefono", nullable=false, length=10)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="correo", length=45)
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="minoristas")
    public Set<Factura> getFacturases() {
        return this.facturases;
    }
    
    public void setFacturases(Set<Factura> facturases) {
        this.facturases = facturases;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="minoristas")
    public Set<Ubicacion> getUbicacioneses() {
        return this.ubicacioneses;
    }
    
    public void setUbicacioneses(Set<Ubicacion> ubicacioneses) {
        this.ubicacioneses = ubicacioneses;
    }




}


