package com.mycompany.models;


// Generated 12/09/2015 04:52:35 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.annotations.NamedQueries;
import org.hibernate.annotations.NamedQuery;

/**
 * Productos generated by hbm2java
 */

@NamedQueries({
    @NamedQuery(name="productosFecha",
            query="SELECT p.productos.nombre FROM ProductoEnVenta p WHERE p.idProductosEnVenta in "
                + "(SELECT d.detalleFactura.productosEnVenta.idProductosEnVenta FROM Despacho d "
                    + "WHERE d.rutas.transportistas.idTransportistas= :transportistaID AND d.rutas.fechaInicio=:fechaID)")
})

@Entity
@Table(name="Productos")
public class Producto  implements java.io.Serializable {


     private Integer idProductos;
     private String nombre;
     private int duracion;
     private boolean refrigeracion;
     private Set<ProductoEnVenta> productosEnVentas = new HashSet<ProductoEnVenta>(0);

    public Producto() {
    }

	
    public Producto(String nombre, int duracion, boolean refrigeracion) {
        this.nombre = nombre;
        this.duracion = duracion;
        this.refrigeracion = refrigeracion;
    }
    public Producto(String nombre, int duracion, boolean refrigeracion, Set <ProductoEnVenta>productosEnVentas) {
       this.nombre = nombre;
       this.duracion = duracion;
       this.refrigeracion = refrigeracion;
       this.productosEnVentas = productosEnVentas;
    }
   
     @Id @GeneratedValue

    
    @Column(name="idProductos", unique=true, nullable=false)
    public Integer getIdProductos() {
        return this.idProductos;
    }
    
    public void setIdProductos(Integer idProductos) {
        this.idProductos = idProductos;
    }

    
    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="duracion", nullable=false)
    public int getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(int duracion) {
        this.duracion = duracion;
    }

    
    @Column(name="refrigeracion", nullable=false)
    public boolean isRefrigeracion() {
        return this.refrigeracion;
    }
    
    public void setRefrigeracion(boolean refrigeracion) {
        this.refrigeracion = refrigeracion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="productos")
    public Set<ProductoEnVenta> getProductosEnVentas() {
        return this.productosEnVentas;
    }
    
    public void setProductosEnVentas(Set <ProductoEnVenta>productosEnVentas) {
        this.productosEnVentas = productosEnVentas;
    }




}


