package com.mycompany.models;
// Generated Sep 8, 2015 3:54:08 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ruta generated by hbm2java
 */
@Entity
@Table(name="Rutas")
public class Ruta  implements java.io.Serializable {


     private int idRutas;
     private Transportista transportistas;
     private String fechaInicio;
     private String fechaFinalizacion;
     private Set<Novedad> novedadeses = new HashSet<Novedad>(0);
     private Set<Despacho> despachoses = new HashSet<Despacho>(0);

    public Ruta() {
    }

	
    public Ruta(int idRutas, Transportista transportistas, String fechaInicio, String fechaFinalizacion) {
        this.idRutas = idRutas;
        this.transportistas = transportistas;
        this.fechaInicio = fechaInicio;
        this.fechaFinalizacion = fechaFinalizacion;
    }
    public Ruta(int idRutas, Transportista transportistas, String fechaInicio, String fechaFinalizacion, Set<Novedad> novedadeses, Set<Despacho> despachoses) {
       this.idRutas = idRutas;
       this.transportistas = transportistas;
       this.fechaInicio = fechaInicio;
       this.fechaFinalizacion = fechaFinalizacion;
       this.novedadeses = novedadeses;
       this.despachoses = despachoses;
    }
   
     @Id 

    
    @Column(name="idRutas", unique=true, nullable=false)
    public int getIdRutas() {
        return this.idRutas;
    }
    
    public void setIdRutas(int idRutas) {
        this.idRutas = idRutas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Transportistas_idTransportistas", nullable=false)
    public Transportista getTransportistas() {
        return this.transportistas;
    }
    
    public void setTransportistas(Transportista transportistas) {
        this.transportistas = transportistas;
    }

    
    @Column(name="fechaInicio", nullable=false, length=45)
    public String getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(String fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    
    @Column(name="fechaFinalizacion", nullable=false, length=45)
    public String getFechaFinalizacion() {
        return this.fechaFinalizacion;
    }
    
    public void setFechaFinalizacion(String fechaFinalizacion) {
        this.fechaFinalizacion = fechaFinalizacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="rutas")
    public Set<Novedad> getNovedadeses() {
        return this.novedadeses;
    }
    
    public void setNovedadeses(Set<Novedad> novedadeses) {
        this.novedadeses = novedadeses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="rutas")
    public Set<Despacho> getDespachoses() {
        return this.despachoses;
    }
    
    public void setDespachoses(Set<Despacho> despachoses) {
        this.despachoses = despachoses;
    }




}


