package com.mycompany.models;


// Generated 12/09/2015 04:52:35 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Transportistas generated by hbm2java
 */
@Entity
@Table(name="Transportistas")
public class Transportista  implements java.io.Serializable {


     private int idTransportistas;
     private String nombres;
     private String apellidos;
     private String telefono;
     private String correo;
     private Set <Ruta>rutases = new HashSet<Ruta>(0);
     private Set <Vehiculo>vehiculoses = new HashSet<Vehiculo>(0);
     private Set <Ubicacion>ubicacioneses = new HashSet(0);

    public Transportista() {
    }

	
    public Transportista(int idTransportistas, String nombres, String apellidos, String telefono) {
        this.idTransportistas = idTransportistas;
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.telefono = telefono;
    }
    public Transportista(int idTransportistas, String nombres, String apellidos, String telefono, String correo, Set <Ruta>rutases, Set<Vehiculo> vehiculoses, Set <Ubicacion>ubicacioneses) {
       this.idTransportistas = idTransportistas;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.telefono = telefono;
       this.correo = correo;
       this.rutases = rutases;
       this.vehiculoses = vehiculoses;
       this.ubicacioneses = ubicacioneses;
    }
   
     @Id 

    
    @Column(name="idTransportistas", unique=true, nullable=false)
    public int getIdTransportistas() {
        return this.idTransportistas;
    }
    
    public void setIdTransportistas(int idTransportistas) {
        this.idTransportistas = idTransportistas;
    }

    
    @Column(name="nombres", nullable=false, length=45)
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    
    @Column(name="apellidos", nullable=false, length=45)
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    
    @Column(name="telefono", nullable=false, length=10)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="correo", length=45)
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="transportistas")
    public Set <Ruta>getRutases() {
        return this.rutases;
    }
    
    public void setRutases(Set <Ruta>rutases) {
        this.rutases = rutases;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="transportistas")
    public Set<Vehiculo> getVehiculoses() {
        return this.vehiculoses;
    }
    
    public void setVehiculoses(Set<Vehiculo> vehiculoses) {
        this.vehiculoses = vehiculoses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="transportistas")
    public Set <Ubicacion>getUbicacioneses() {
        return this.ubicacioneses;
    }
    
    public void setUbicacioneses(Set <Ubicacion>ubicacioneses) {
        this.ubicacioneses = ubicacioneses;
    }




}


