package com.mycompany.models;
// Generated Sep 8, 2015 3:54:08 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Vehiculo generated by hbm2java
 */
@Entity
@Table(name="Vehiculos")
public class Vehiculo  implements java.io.Serializable {


     private String placa;
     private Transportista transportistas;
     private float capacidad;
     private String tipoVehiculo;

    public Vehiculo() {
    }

    public Vehiculo(String placa, Transportista transportistas, float capacidad, String tipoVehiculo) {
       this.placa = placa;
       this.transportistas = transportistas;
       this.capacidad = capacidad;
       this.tipoVehiculo = tipoVehiculo;
    }
   
     @Id 

    
    @Column(name="placa", unique=true, nullable=false, length=6)
    public String getPlaca() {
        return this.placa;
    }
    
    public void setPlaca(String placa) {
        this.placa = placa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Transportistas_idTransportistas", nullable=false)
    public Transportista getTransportistas() {
        return this.transportistas;
    }
    
    public void setTransportistas(Transportista transportistas) {
        this.transportistas = transportistas;
    }

    
    @Column(name="capacidad", nullable=false, precision=12, scale=0)
    public float getCapacidad() {
        return this.capacidad;
    }
    
    public void setCapacidad(float capacidad) {
        this.capacidad = capacidad;
    }

    
    @Column(name="tipoVehiculo", nullable=false, length=20)
    public String getTipoVehiculo() {
        return this.tipoVehiculo;
    }
    
    public void setTipoVehiculo(String tipoVehiculo) {
        this.tipoVehiculo = tipoVehiculo;
    }




}


